export const subjects = {
  1: [
    'Matematika 2',
    'Uvod u informacione sisteme',
    'Engleski jezik u menadžmentu 1',
    'Principi programiranja',
    'Psihologija',
    'Osnove operacionog menadžmenta',
    'Inženjering procesa (NA)',
    'Sociologija',
    'Menadžment tehnologije i razvoja (NA)'
  ],
  2: [
    'Baze podataka',
    'Ekonomika poslovanja i planiranje',
    'Standardizacija',
    'Cloud infrastruktura i servisi',
    'Statistika',
    'Osnove operacionog menadžmenta',
    'Strukture podataka i algoritmi',
    'Finansijski menadžment i računovodstvo',
    'Inženjering procesa (NA)',
    'Računovodstvo',
    'Osnove finansijskog menadžmenta',
    'Uvod u poslovnu analitiku',
    'Interakcija čovek-računar',
    'Programiranje 2 (NA)',
    'Klijentske veb tehnologije i skriptni jezici',
    'Jezici i okruženja za razvoj IS',
    'Programski jezici za analitiku',
    'Menadžment tehnologije i razvoja (NA)'
  ],
  3: [
    'Ekonometrijske metode',
    'Operaciona istraživanja 2',
    'Upravljanje promenama',
    'Finansijska tržišta',
    'Programski jezici',
    'Interpersonalne veštine u organizaciji',
    'Planiranje proizvodnje i usluga',
    'Trening i razvoj',
    'Statistička kontrola procesa',
    'Upravljanje kvalitetom projekta',
    'Linearni statistički modeli',
    'Digitalni marketing',
    'Numerička analiza',
    'Osnove programiranja',
    'Sistem menadžmenta kvaliteta',
    'Ekološki menadžment',
    'Preduzetništvo',
    'Veštačka inteligencija',
    'Planiranje kvaliteta',
    'Međunarodni menadžment',
    'Zaštita računarskih sistema',
    'Upravljanje dokumentacijom',
    'Metode optimizacije',
    'Kontrola kvaliteta',
    'Analiza i logičko projektovanje IS (projekat)',
    'Napredne Java tehnologije',
    'Serverske veb tehnologije',
    'ETL i skladišta podataka',
    'Upravljačko računovodstvo',
    'Matematika 3',
    'Upravljanje investicijama',
    'Metrologija i normativno regulisanje kvaliteta',
    'Upravljanje inovacijama',
    'Menadžment proizvodnje i pružanja usluga',
    'Poslovni informacioni sistemi',
    'Upravljanje troškovima'
  ],
  4: [
    'Akreditacija i sertifikacija',
    'Analiza finansijskih izveštaja i vrednovanje preduzeća',
    'Analiza podataka',
    'Bankarski menadžment',
    'Biostatistika',
    'Eko-marketing',
    'Ekonometrijske metode',
    'Engleski jezik struke 3',
    'Internet inteligentnih uređaja',
    'Internet marketing',
    'Inteligentni sistemi',
    'Linearni statistički modeli',
    'Mašinsko učenje',
    'Matematički modeli efikasnosti',
    'Meko računanje',
    'Međunarodni marketing',
    'Menadžment proizvodnje i pružanja usluga',
    'Menadžment specijalnih događaja',
    'Mobilno računarstvo',
    'Multimedijalna produkcija',
    'Napredno programiranje',
    'Napredne Java tehnologije',
    'Odabrana poglavlja iz Menadžmenta kvaliteta 2',
    'Odnosi s medijima',
    'Ocena kvaliteta poslovnog sistema',
    'Osnove kvaliteta',
    'Osnove teorije igara',
    'Projektovanje organizacije',
    'Projektovanje proizvodnih sistema',
    'Razvoj malih i srednjih preduzeća',
    'Softverska podrška upravljanju projektima',
    'Statističko zaključivanje',
    'Strateški menadžment',
    'Upravljanje lancima snabdevanja 1',
    'Upravljanje malim i srednjim preduzećima',
    'Upravljanje prodajom',
    'Upravljanje rizikom u e-poslovanju',
    'Uvod u menadžment elektronskog poslovanja',
    'Uvod u neuronske mreže',
    'Zaštita računarskih sistema'
  ]
} as const;

export type Year = keyof typeof subjects;
